# Generated by Django 3.1.4 on 2020-12-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.userprofile')),
                ('restaurant_name', models.CharField(max_length=30)),
                ('description', models.CharField(default='', max_length=250)),
            ],
            bases=('accounts.userprofile',),
        ),
    ]
