# Generated by Django 3.1.4 on 2020-12-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201209_1142'),
        ('restaurants', '0002_auto_20201208_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='name',
            new_name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='id',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='userprofile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
