# Generated by Django 3.1.4 on 2020-12-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmeals',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurants'),
        ),
    ]
