# Generated by Django 3.1.4 on 2020-12-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmeals',
            name='is_eatable',
            field=models.BooleanField(default=True),
        ),
    ]
