# Generated by Django 3.1.4 on 2020-12-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20201208_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmeals',
            name='picture',
            field=models.ImageField(blank=True, upload_to='public/meals/'),
        ),
    ]
