# Generated by Django 3.1.4 on 2020-12-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20201210_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantmeals',
            old_name='creator',
            new_name='userprofile_ptr_id',
        ),
    ]
