# Generated by Django 3.1.4 on 2020-12-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20201209_1142'),
        ('meals', '0003_auto_20201208_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmeals',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurants'),
            preserve_default=False,
        ),
    ]
