# Generated by Django 3.1.4 on 2020-12-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20201209_1142'),
        ('meals', '0004_restaurantmeals_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmeals',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurants'),
        ),
    ]
