# Generated by Django 3.1.4 on 2020-12-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20201210_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantmeals',
            old_name='userprofile_ptr_id',
            new_name='userprofile_ptr',
        ),
    ]
