# Generated by Django 3.1.4 on 2020-12-10 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('meals', '0007_auto_20201210_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmeals',
            name='userprofile_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
