# Generated by Django 3.1.4 on 2020-12-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('meals', '0009_auto_20201210_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmeals',
            name='userprofile_ptr',
        ),
        migrations.AddField(
            model_name='restaurantmeals',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurants'),
            preserve_default=False,
        ),
    ]
