# Generated by Django 3.1.4 on 2020-12-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_auto_20201210_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmeals',
            name='picture',
            field=models.ImageField(blank=True, default='public\\defaults/default_meal.png', upload_to='public/meals/'),
        ),
    ]
