# Generated by Django 3.1.4 on 2020-12-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_auto_20201210_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmeals',
            name='picture',
            field=models.ImageField(default='public\\defaults/default_meal.png', upload_to='public/meals/'),
        ),
    ]
