# Generated by Django 3.1.4 on 2020-12-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201208_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='amount_of_purchases',
            new_name='sales_or_purchase',
        ),
    ]
