# Generated by Django 3.1.4 on 2020-12-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201209_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
