# Generated by Django 3.1.4 on 2020-12-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_is_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/public/restaurants/restaurant.png', upload_to='private/users/'),
        ),
    ]
