# Generated by Django 3.1.4 on 2020-12-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201209_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='public\\defaults/default_avatar.jpg', upload_to='private/users/'),
        ),
    ]
